csun-metalab/affinity

- app/helpers.php
> ENG: Adjust JSON header values to be all strings.

- app/Http/Controllers/InterestsController.php
We want to do the following
If a user is not found return the error response.
If the email is blank return the error response.
This task is done when all the interest routes with the email filter work this way
> AFFINITY-55: ENG: Error Code adjustments

- app/Http/routes.php
- resources/views/home.blade.php
So we currently have hard coded emails on the urls for the front end.that do not work when the applications is in development mode.
To solve this issue we would want to be able to dynamically generate the email based on app environment.
This task is done when
* App environment is local and the email on the front end starts with nr_
* App environment is production ( or anything other than local ) and the email on the front end doesn't start with nr_
> AFFINITY-58: Dynamically display email based on app environment

- app/Http/Controllers/InterestsController.php
For this task we'll want to use the ```$request->getQueryString()``` helper.
With this we want to check for if the ```email``` query is in the URI
We also want to check to see if the query string is NULL
finally we throw a NadRequestExceptiion.
This task is done when all three cases are taken into consideration.
The following branch has somewhat helpful code
task-restore-research
> AFFINITY-63:Re-write handleInterestType method

- app/Http/Controllers/InterestsController.php
Mistakes were made.
task-restore-research
> Restore the research interest code.

- resources/views/home.blade.php
On the frontend, both Collection and Subsection section must match by listing badges first and interests second.  
-Modified Collection section to list badges first.
> AFFINITY 40 -  Make frontend sections consistent

- app/Http/Controllers/InterestsController.php
- app/Http/routes.php
- app/Models/Academic.php
- app/Models/InterestEntity.php
- resources/views/home.blade.php
Edited academic interest model to point to an appropriate table in database.
Completed change to Route to include API.
Created function in InterestEntity model to attempt to join Research Interest flagged as academic interest.
Will return a listing of academic interest.
**READY**
NO
Fixes issues with academic interest routes pointing to the incorrect database table.
Creates a function in the InterestEntity model which will filter connections flagged with the academic flag. It will attempt to retrieve such research interest. 
Test academic routes:
http://affinity.app/api/1.0/interests/academic
http://affinity.app/api/1.0/interests/academic?email=nr_jeffrey.wiegley@csun.edu
None
http://affinity.app/api/1.0/interests/academic
http://affinity.app/api/1.0/interests/academic?email=nr_jeffrey.wie …
> AFF-64 : Academic Interest Fix DB:TABLE 

- app/Http/routes.php
- resources/views/home.blade.php
- resources/views/pages/about/version-history.blade.php
We want to document the changes that have taken place in the application.
Here are a few examples
[http://www.csun.edu/faculty/about/version-history]
[http://www.csun.edu/faculty/beta/scholarship/about/version-history]
This task is done when
* We have a version history about page
> AFFINITY-69 UI: Add an About page that lists the version history changes

- app/Http/Controllers/InterestsController.php
- app/Models/InterestEntity.php
`READY`
`NO`
`This fixes the functionality for academic research interest look up work`
`Look at InterestEntity@50`
`None`
`NO`
`Search people's academic interests. For example Nerces has two`
`InterestEntity.php`
> Make the look-up for academic research function.

- app/Exceptions/Handler.php
- app/Http/Controllers/BadgesController.php
- app/Http/Controllers/InterestsController.php
Added more diversity in the error feedback for the functions in InterestsController.php. Includes changes made to Handler.php to accomodate for the new exceptions being used.
READY
NO
Changes the exception messages to provide more useful feedback. There is no longer just one generic error message.
InterestsController.php
Test several URLs to observe the exceptions in action, such as:
`affinity/public/api/1.0/interests?email=`
`affinity/public/api/1.0/interests?email=blah`
`affinity/public/api/1.0/interests/blah`
`affinity/public/api/1.0/interests/personal?email=`
InterestsController.php
Handler.php
> AFFINITY-72 - Reworked exceptions and error messages

- tests/BadgesControllerTest.php
`READY`
`NO`
This PR creates a unit test for getAllIndivudalsByBadge.  Outputs tested are:
1)Status code is 200
2)Count is 42
3)Count matches the amount of individuals returned
4)Collection is 'badges
Note:  A parameter was added to BadgesControllerTest@makeAssertionsForStatusAndCount.
` BadgesControllerTest`
`vendor/bin/phpunit`
`Testing Only`
> testing/AFFINITY-78 Write PHPUnit test for: BadgesController@getAllIndivudalsByBadge

- app/Http/Controllers/BadgesController.php
- tests/BadgesControllerTest.php
- tests/InterestsControllerTest.php
READY
`YES | NO`
`This PR provides 5 unit tests for @handleBasedOnQuery.  Also one modification is made in InterestControllerTest`
`BadgesControllerTest`
`vendor/bib/phpunit`
`Testing Only`
> testing/AFFINITY-82 Created 5 functions to test BadgesController@handleBasedOnQuery

- app/Http/Controllers/InterestsController.php
- tests/InterestsControllerTest.php
READY
NO
Implements 9 functions to test handleInterestType().
The functions test:
When type is research
When type is personal
When type is academic
When a valid e-mail is given for each of the 3 types.
Checks if the status code is 406, 
InterestsControllerTests
phpunit
> testing/AFFINITY-85 Write PHPUnit test for: InterestController@handleInterestType

- tests/InterestsControllerTest.php
READY
NO
Implements 2 functions to test getAllInterests().
The functions test:
All 1819 interests are returned when no e-mail is given,
When a valid e-mail is given , and the appropriate number of interests is returned,
For a status code of 200.
InterestsControllerTest.php
phpunit
> testing/AFFINITY-86 Write PHPUnit test for: InterestController@getAllInterests

- resources/views/home.blade.php
- resources/views/pages/about/version-history.blade.php
`READY`
`NO`
`Prepares Affinity for 1.0 release`
`Landing page and about page`
`NONE`
`NONE`
`Test whole application`
`Landing page and about page`
> AFFINITY-96 UI: In preparation for the release of affinity we want to update the version history.

- app/Models/InterestEntity.php
`**READY**`
`YES`
`Fix lack of error handling`
`InterestEntity.php`
`NONE`
`NONE`
`Find someone who does not have any academic interests`
`Academic interests listing`
> Add error checking for academic interests.

- app/Http/Controllers/BadgesController.php
`**READY/HOLD**`
`YES | NO`
`What does this pull request achieve? How does it impact the application.`
`What piece of the code received the most attention and your reviewer should start by looking at?`
`List related PRs against other branches:`
branch | PR
------ | ------
`other_pr_production` | `[link]()`
`Where any changes made to packages or dependencies? Will anything require updating to replicate pull request environment.`
`Outline the steps to test or reproduce the PR here.`
i.e.:
```sh
git pull --prune
git checkout <feature_branch>
bundle; script/server
```
`List general components of the application that this PR will affect:`
> HOTFIX-10-05-17: Switch out the Person model to the User model.

- .env.example
- bootstrap/app.php
- composer.json
- composer.lock
- config/forcehttps.php
`**READY**`
`NO`
`Adds force-https and registers the proxypass package`
`Add FORCE_HTTPS=true or false`
`None`
`New dependency lumen-force-https package`
`Run composer install`
`Add FORCE_HTTPS=true or false to env`
`The whole application`
> Add force-https and register proxypass package.

- bootstrap/app.php
- composer.json
- composer.lock
- config/cors.php
- routes/api.php
This task adds the CORS package that mitigates the CORS error.
> task-add-cors

- docker-compose.yml
```
docker-compose.yml file for web api affinity
```
```
Have the docker-compose.yml file in affinity directory
Have testing .env from web-demo-php7 server
```
1. Clone media repository: `git clone https://github.com/csun-metalab/affinity.git`
2. Obtain testing .env from web-demo-php7 server
3. Import affinity's docker-compose.yml file if it isn't merged yet
4. Run `docker-compose up -d`
> added docker-compose.yml file for affinity
